add-web-push
openearthplatforminitiative/flood-frontend pull request #1
Opened 2023-10-11 11:21 UTC by henrikav

First shell of web push up. Needs some more testing on pc and mobile

2023-10-13 09:54 UTC, dymbe requested changes
Seems to work fine on Firefox and Mac, although it does not allow me to send the same notification twice (I assume that's a feature not a bug?). I have some suggestions, also I think you should run the formatter

2023-10-13 09:54 UTC, dymbe commented on app/api/register-push/route.ts
> +export async function GET(_: NextRequest) {
Would move this to a different folder, as it does not GET a push-registration. For example `app/api/push`? Would consider making this a POST-endpoint instead, as this makes more sense for REST (you're creating a push-notification, not getting it), although you could keep this a GET if that makes testing easier

2023-10-13 09:54 UTC, dymbe commented on app/api/register-push/route.ts
> +import {deleteSubscriptionFromDb, getSubscriptionsFromDb, saveSubscriptionToDb } from '@/app/utils/in-memory-db'
Could you rename this folder to something like `push-subscriptions` or just `subscriptions` to make the API more RESTful?

2023-10-13 09:54 UTC, dymbe commented on app/api/register-push/route.ts
> +        const subscriptionToDelete: PushSubscription | undefined = await request.json();
Is it possible for `subscriptionToDelete` to be `undefined` here? I think `request.json()` will just throw an error if it has no data

2023-10-13 09:54 UTC, dymbe commented on app/utils/in-memory-db.ts
> +import {PushSubscription as DatabasePushSubscription} from 'web-push';
I would consider moving the util-folder out of the app-router folder

2023-10-13 09:54 UTC, dymbe commented on public/manifest.json
> +{
This file probably needs some more work, but it's fine to not prioritize it right now. Would create an issue for it though

2023-10-13 09:54 UTC, dymbe commented on public/service.js
> +self.addEventListener('push', async (event) => {
could you rename this to `service-worker.js`? Or `sw.js`. It's not obvious to me that this is a service-worker

2023-10-13 09:54 UTC, dymbe commented on app/page.tsx
> +    useEffect(() => {
What do you think about merging the useEffect calls here?

2023-10-16 06:40 UTC, henrikav commented on public/manifest.json
> +{
Done

2023-10-16 06:43 UTC, henrikav commented on app/api/register-push/route.ts
> +        const subscriptionToDelete: PushSubscription | undefined = await request.json();
If the request body is empty or doesn't contain valid JSON data, the await request.json() call can result in undefined

2023-10-16 06:49 UTC, henrikav commented on app/api/register-push/route.ts
> +export async function GET(_: NextRequest) {
I agree. Moved into push-notification folder but kept as GET.

2023-10-16 06:49 UTC, henrikav commented on app/api/register-push/route.ts
> +import {deleteSubscriptionFromDb, getSubscriptionsFromDb, saveSubscriptionToDb } from '@/app/utils/in-memory-db'
Done

2023-10-16 06:49 UTC, henrikav commented on app/utils/in-memory-db.ts
> +import {PushSubscription as DatabasePushSubscription} from 'web-push';
Done

2023-10-16 06:50 UTC, henrikav commented on public/service.js
> +self.addEventListener('push', async (event) => {
Done

2023-10-16 06:50 UTC, henrikav commented on app/page.tsx
> +    useEffect(() => {
I agree, done.

2023-10-16 08:42 UTC, dymbe requested changes
Looks good as PoC for now, except for one little nitpick

2023-10-16 08:42 UTC, dymbe commented on README.md
>  =======
This looks like the leftovers of a merge-conflict

2023-10-16 10:05 UTC, dymbe approved these changes

2023-10-16 13:08 UTC, merged