fix: improves the readme files and organize them into their respective folders
openearthplatforminitiative/flood-frontend pull request #33
Opened 2024-10-23 13:15 UTC by kroglid

Adds more details about Pulumi and how to configure the config
Adds prerequisites to root README.md
Adds a step guide in root README.md with links to more detailed config guides
Moves configs to their respective folders

2024-10-23 13:27 UTC, daniejoh requested changes
Some small changes :)

2024-10-23 13:27 UTC, daniejoh commented on keycloak/README.md
> +Found in the `keycloak` folder. The image is based on the official Keycloak image, but with additional build time configuration and a custom realm. The realm is defined in the `realm.json` file, and
> Found in the `keycloak` folder.

We already are in this folder.

2024-10-23 13:27 UTC, daniejoh commented on frontend/README.md
> +- `KEYCLOAK_ID` - The client ID of the Keycloak client
How can I find this?

2024-10-23 13:27 UTC, daniejoh commented on frontend/README.md
> +- `KEYCLOAK_ID` - The client ID of the Keycloak client
And is there any default?

2024-10-23 13:27 UTC, daniejoh commented on infrastructure/README.md
> +To tear down pulumi, use `pulumi destroy`.
We dont tear down pulumi. We tear down infrastructure _with_ pulumi.

2024-10-23 13:40 UTC, daniejoh approved these changes

2024-10-28 07:30 UTC, kstigen approved these changes

2024-11-01 12:42 UTC, merged