feature/add-site-map
openearthplatforminitiative/flood-frontend pull request #5
Opened 2023-11-15 06:50 UTC by henrikav

WIP

2023-11-30 13:57 UTC, dymbe requested changes
I think it was a bit difficult to get an overview of the code. All onboarding components are getting quite complicated together.

This might have gotten easier if we used next-pages more extensively, but we would need to find out how and when we want to save data during the onboarding process in that case

2023-11-30 13:57 UTC, dymbe commented on app/[lang]/layout.tsx
> +          crossOrigin=""
Do you need this if it's just empty anyway?

2023-11-30 13:57 UTC, dymbe commented on app/api/geocoding/reverse/route.ts
> +      `https://api-test.openepi.io/geocoding/reverse?lat=${lat}&lon=${lon}`
`https://api-test.openepi.io` should probably be inserted via an environment variable

2023-11-30 13:57 UTC, dymbe commented on app/api/geocoding/reverse/route.ts
> +      status: 200,
the HTTP status code shouldn't be in the JSON response body, it should be specified like you do on line 23 I'm not sure if we need the `message`-column there either, but you can make that call.

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/AddNewSite.tsx
> +const AddNewSitePosition = dynamic(
Is this necessary? I tried importing it the regular way and had no errors so far

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/AddNewSite.tsx
> +  const [radius, setRadius] = useState<number>(0);
Is this radius related to the radius in `SiteData`?

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/AddNewSite.tsx
> +            JSON.parse(siteValues.position).lat
Can retrieving the lat and lon be done in a preceding step to make this more readable? Also why is siteValues.position a JSON-string?

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/AddNewSite.tsx
> +        setPositionInfo(data.city + ', ' + data.country);
Somewhat subjective, but I think this is more readable with string interpolation:

```javascript
setPositionInfo(`${data.city}, ${data.country}`);
```

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/OnboardingDashboard.tsx
> +  const [siteToView, setSiteToView] = useState<number>(-1);
I think it is more clear if null or undefined is used to represent that no site is selected at the moment

2023-11-30 13:57 UTC, dymbe commented on app/components/onboarding/SiteMap.tsx
> +  const center: LatLngExpression = [51.505, -0.09];
I guess this is a placeholder?

2023-11-30 14:01 UTC, dymbe commented on prisma/migrations/0_init/migration.sql
> +    "positionInfo" TEXT NOT NULL,
If you want positionInfo to always contain the city and the country that the site is in, I would rather that you just store that as two separate fields here to make it clear and easier to use

2023-12-01 08:26 UTC, henrikav commented on app/components/onboarding/AddNewSite.tsx
> +  const [radius, setRadius] = useState<number>(0);
Yes! I will improve this by only using the radius in sitedata

2023-12-05 12:07 UTC, dymbe requested changes

2023-12-05 12:07 UTC, dymbe commented on app/api/geocoding/reverse/route.ts
> +    const response = await fetch(
You don't have do this in in this PR, but you can now use the `openepi-client-js` package for this:
https://www.npmjs.com/package/openepi-client

2023-12-05 12:07 UTC, dymbe commented on app/components/onboarding/Sites.tsx
>              {(values || []).sites.map((site, index) => {
`[]` as a default value will immediately fail due to `.sites` not existing on an array. I assume you meant to do

```javascript
{(values.sites || []).map((site, index) => {
```

2023-12-05 12:07 UTC, dymbe commented on prisma/migrations/0_init/migration.sql
> +-- CreateTable
It seems like this migration was not made using `prisma migrate dev` as the folder does not follow the usual naming convention used by prisma?

2023-12-05 12:07 UTC, dymbe commented on prisma/schema.prisma
> +model LatLng {
I think it might be a bit of an overkill to create a whole new table to store coordinates. Could this be two fields on `Site` instead?

2023-12-06 11:46 UTC, dymbe approved these changes
Could only see one minor nitpick, LGTM

2023-12-06 11:46 UTC, dymbe commented on app/components/onboarding/AddNewSite.tsx
> +    console.log('Values: ', siteValues);
This seems like debugging-code, consider removing it

2023-12-06 11:48 UTC, merged